python train.py --runno 2 \
    --model_type lstm \
    --max_epochs 100 \
    --base_lr 0.005 \
    --verbose \
    --num_decoder_layers 5 \
    --num_encoder_layers 5 \
    --num_dense_layers 7 \
    --d_model 512 \
    --detect_anomaly \
    --enable_autocast \
    --layer_norm_eps 0.01 \
    --batch_size 256 \
    --lstm_input_size 64